[project]
name = "advent-of-code-2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ruff>=0.14.9",
    "pre-commit>=4.0.1",
    "numpy>=2.3.5",
    "scipy>=1.16.3",
]
